### ISSUE TITLE
'module' object has no attribute 'HttpClient'

### ISSUE THREAD

**Issue by kozbo** [ga4gh/ga4gh-client#12]
Created a new virtualenv
pip install ga4gh_client  --no-cache-dir --pre ga4gh_client
pip install jupiter
jupiter notebook
- then run 1kg_bio_metadata_service.ipynb
(can be found here: https://github.com/achave11/bioapi-examples/blob/notebook_examples/python_notebooks/1kg_bio_metadata_service.ipynb)
step through the first code block and get the following error when trying to initialize the httpClient:

code:
```
import ga4gh_client as client
c = client.HttpClient("http://1kgenomes.ga4gh.org") 
```
Error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-b2f2f769182e> in <module>()
      1 import ga4gh_client as client
----> 2 c = client.HttpClient("http://1kgenomes.ga4gh.org")

AttributeError: 'module' object has no attribute 'HttpClient'
```

Also tried in console:
```
>>> import ga4gh_client as client
>>> c = client.HttpClient("http://1kgenomes.ga4gh.org") 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'HttpClient'
```

**Comment by dcolligan** [comment]
Yes, that's expected behavior.  The `HttpClient` class is in the `client` module.  So you need to do:
```
>>> import ga4gh_client.client as client
>>> client.HttpClient
<class 'ga4gh_client.client.HttpClient'>
```

**Comment by kozbo** [comment]
OK, yep, that works. Thanks!
