### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by david4096** [ga4gh/ga4gh-client#5]

**Comment by dcolligan** [comment]
The client is on pypi: https://pypi.python.org/pypi/ga4gh-client

This is the release I uploaded:
https://github.com/ga4gh/ga4gh-client/releases/tag/0.0.1

To install:
```
$ pip install --no-cache-dir --pre ga4gh_client
```
To use:
```
$ python
>>> import ga4gh_client
```
